services:
  travelcompanion.bootstrapper:
    build:
      context: ./API
      dockerfile: ./src/Bootstrapper/TravelCompanion.Bootstrapper/Dockerfile
      target: debug
    depends_on:
      travelcompanion-postgres:
        condition: service_healthy
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
      - ASPNETCORE_ENVIRONMENT=debug
      - ASPNETCORE_URLS=http://+:5000
      - postgres__connectionString=Host=travelcompanion-postgres;Database=travelCompanion;Username=postgres;Password=postgres
      - postgres__hangfireConnectionString=Host=travelcompanion-postgres;Database=travelCompanionHangfire;Username=postgres;Password=postgres
    ports:
      - "5000:5000"
      - "5005:5005"
    networks:
      - travelcompanion-network

  travelcompanion-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travelCompanion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./API/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      retries: 10
    networks:
      - travelcompanion-network

  travelcompanion-ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./UI/src:/app/src
      - /node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - travelcompanion.bootstrapper
    networks:
      - travelcompanion-network

volumes:
  postgres_data:


networks:
  travelcompanion-network:
    driver: bridge
