services:
  travelcompanion.bootstrapper:
    build:
      context: .
      dockerfile: src/Bootstrapper/TravelCompanion.Bootstrapper/Dockerfile
    depends_on:
      travelcompanion-postgres:
        condition: service_healthy
    environment:
      - postgres__connectionString=Host=travelcompanion-postgres;Database=travelCompanion;Username=postgres;Password=postgres
      - postgres__hangfireConnectionString=Host=travelcompanion-postgres;Database=travelCompanionHangfire;Username=postgres;Password=postgres
    ports:
      - "5000:5000"

  travelcompanion-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travelCompanion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      retries: 10

volumes:
  postgres_data: