@module1Url = http://localhost:5000/module1-module
@speakersUrl = http://localhost:5000/speakers-module
@hostId = 28984bfd-9bf5-4284-9f04-717b3e32a542
@speakerId = 37f74d6f-d931-4e02-82f9-fba4d05e393c

<!-- CONFERENCES/HOSTS  -->

###
GET {{module1Url}}/hosts

###
GET {{module1Url}}/hosts/{{hostId}}

###
POST {{module1Url}}/hosts
Content-Type: application/json

{
    "name" : "Host #2",
    "desciption" : "Lorem ipsum" 
}

###
PUT {{module1Url}}/hosts/{{hostId}}
Content-Type: application/json

{
    "name":"Host #999"
}



<!-- SPEAKERS  -->


###
POST {{speakersUrl}}/speakers
Content-Type: application/json

{
    "email": "test@test.pl",
    "name": "Jan",
    "surname": "Kowalski",
    "bio": "lorem ipsum",
    "avatarUrl": "testurl"
}

###
GET {{speakersUrl}}/speakers

###
GET {{speakersUrl}}/speakers/{{speakerId}}

###
PUT {{speakersUrl}}/speakers/{{speakerId}}
Content-Type: application/json

{
    "name": "updated name",
    "surname": "updated surname",
    "email": "updated email",
    "bio": "updated bio",
    "avatarUrl": "new url"
}

###
DELETE {{speakersUrl}}/speakers/{{speakerId}}